version: '3'
services:
  api:
    container_name: backend
    build: .
    volumes:
      - .:/app  
    ports:
      - 8080:8080
    networks:
      - share-network
networks:
  share-network:
    external: true