import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

export async function getServerSideProps() {
  const API_URL = process.env.API_URL
  const res = await fetch(`${API_URL}/hello?name=Next`)
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}
export default function Home(props: any) {
  const API_URL = process.env.NEXT_PUBLIC_API_URL
  console.log(process.env.NEXT_PUBLIC_API_URL)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello Cloud Run SNS</h1>
      </main>
    </>
  )
}
